### ISSUE TITLE
How would I fix this, or is it not possible?

### ISSUE THREAD

**Issue by ArenMejiaYT** [mishalhossin/Discord-G4F-Chatbot#181]
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/69426364/c4f57dc2-204e-4324-bf9b-9fb6cd220763)

**Comment by mishalhossin** [comment]
maybe its down ?

**Comment by ArenMejiaYT** [comment]
ah wait wrong picture sorry, how about this? 
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/69426364/1597a064-c40a-43b6-8e3c-825cda670950)

**Comment by IkdanYT** [comment]
Update code

**Comment by mishalhossin** [comment]
#185
