### ISSUE TITLE
after updating main.py

### ISSUE THREAD

**Issue by thirsty-12** [mishalhossin/Discord-G4F-Chatbot#184]
Traceback (most recent call last):
  File "/home/runner/TOPG/utilities/ai_utils.py", line 94, in generate_response
    response_data = await response.json()
  File "/home/runner/TOPG/venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://chat-aim.vercel.app/api/openai/v1/chat/completions')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/TOPG/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 133, in on_message
    response = await generate_response(instructions, search_results, history, file_content)
  File "/home/runner/TOPG/utilities/ai_utils.py", line 101, in generate_response
    print(f"\033[91mAn error occurred during the API request: {e} \n Response : {response_data}\033[0m")
UnboundLocalError: local variable 'response_data' referenced before assignment

**Comment by selajuf** [comment]
++

**Comment by curiousartem** [comment]
API is currently down.

**Comment by spadesoface** [comment]
any estimates?

**Comment by curiousartem** [comment]
none

**Comment by Aryan2-1** [comment]
It's still down

**Comment by mach7** [comment]
Seems to me that API is being hosted on a vercel.app account and the account is either disabled or suspended. Be nice to have the api too so that the code was dependable to use. Its the best one that is out there. All the other bots that I have tried just don't work.

**Comment by IkdanYT** [comment]
Buy PrismGPT

**Comment by mach7** [comment]
![Screenshot_3](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/5378072/e32f7c86-9798-4cd6-a72a-81754da152eb)
Not any better if we can't get to the site...

**Comment by mishalhossin** [comment]
#185
